; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.3.2 on Mon Sep 13 2021 16:36:36 GMT+0200 (centraleuropeisk sommartid)
; insert codes for deploying the Z probe here

